dataset: "sevenScenesDataset"
root: "/mnt/pfs/data/RGBD/7Scenes"
h: 384
w: 512
clip_length: 20
clip_overlap: 5
split: "test"

model_name: "DepthCrafter"
model_params:  #
  model_dir: "/mnt/pfs/users/sunyangtian/Depth/DepthCrafter"
  unet_path: "/mnt/pfs/users/sunyangtian/pretrained/DepthCrafter"
  pre_train_path: "/mnt/pfs/users/sunyangtian/pretrained/stable-video-diffusion-img2vid-xt"


eval_depth:
  metric_names: 
    - 'Abs Rel'
    - 'delta < 1.25'
    - 'delta < 1.25^2'
    - 'delta < 1.25^3'
  depth_alignment: "lstsq"