dataset: "ScannetPPDataset"
root: "/mnt/pfs/data/scannetpp_processed_iphone_IMU"
h: 384
w: 512
clip_length: 25
clip_overlap: 5
split: "test"

model_name: "DepthCrafter"
model_params:  #
  model_dir: "/mnt/pfs/users/sunyangtian/Depth/DepthCrafter"
  unet_path: "/mnt/pfs/users/sunyangtian/pretrained/DepthCrafter"
  pre_train_path: "/mnt/pfs/users/sunyangtian/pretrained/stable-video-diffusion-img2vid-xt"


eval_depth:
  metric_names: 
    - 'Abs Rel'
    - 'delta < 1.25'
    - 'delta < 1.25^2'
    - 'delta < 1.25^3'
  depth_alignment: "lstsq"

eval_normal:
  metric_names: 
    - 'normal mean'
    - 'normal median'
    - 'angle < 7.5'
    - 'angle < 11.25'
  
vis_depth: True