dataset: "ScannetPPDataset"
root: "/mnt/pfs/data/scannetpp_processed_iphone_IMU"
h: 384
w: 512
clip_length: 25
clip_overlap: 5
split: "test"

model_name: "StableNormal"
model_params:  #
  model_dir: "/mnt/pfs/users/sunyangtian/Depth/StableNormal"


eval_normal:
  metric_names: 
    - 'normal mean'
    - 'normal median'
    - 'angle < 7.5'
    - 'angle < 11.25'
  
vis_depth: True